### ISSUE TITLE
Sidebars are appearing in fullscreen and theater mode

### ISSUE THREAD

**Issue by LostOdin** [WesselKroos/youtube-ambilight#187]
### Bug description

When in theater mode the black bars appear, same as about a month and a half ago

### Steps to reproduce the behavior

![Opera Snapshot_2023-08-18_123451_www youtube com](https://github.com/WesselKroos/youtube-ambilight/assets/142619750/5de8aeba-f835-4113-b7fe-7f34e10cc937)
Much like a month and a half ago when youtube update theater mode the black bars on the side overlap the ambient feature. Also the hide everything when in theater more isn't working

### Browser

Opera

### Operating system

Windows

### Extension version

2.39.29

### The bug still happens in these conditions

- [X] The bug still persist when I disable all other extensions (ex. in incognito mode with only this extension enabled)
- [X] When I logged out of my YouTube account (ex. in incognito mode)
- [X] In incognito mode

**Comment by WesselKroos** [comment]
Hmm... Funny, they keep renaming the theater mode element.
1.5 months ago it was renamed from `player-theater-container` to `player-wide-container`.
Now it has been renamed to `player-full-bleed-container`.

Anyway, I'll submit version 2.39.30 to the extension stores with the new name. Publication can take a while since the weekend starts now. 
If you manually want to fix it here is are the css rules you'll need:

``` css
html[data-ambientlight-enabled=true] ytd-app #player-full-bleed-container {
  background: none !important;
}

html[data-ambientlight-enabled=true] ytd-app #player-full-bleed-container {
  transition: background-color 0s 0.01s;
}

html[data-ambientlight-enabled=true][data-ambientlight-immersive=true] ytd-watch-flexy[theater] #player-full-bleed-container.ytd-watch-flexy {
  height: calc(100vh - 169px) !important;
  max-height: calc(100vh - 169px) !important;
  margin-top: 29px;
  margin-bottom: 84px;
}
```

**Comment by MoisteryMachine** [comment]
Hey, just wanted to say I'm experiencing the same and that css fix worked, thank you very much! <3

**Comment by Desoroxxx** [comment]
> Hmm... Funny, they keep renaming the theater mode element. 1.5 months ago it was renamed from `player-theater-container` to `player-wide-container`. Now it has been renamed to `player-full-bleed-container`.
> 
> Anyway, I'll submit version 2.39.30 to the extension stores with the new name. Publication can take a while since the weekend starts now. If you manually want to fix it here is are the css rules you'll need:
> 
> ```css
> html[data-ambientlight-enabled=true] ytd-app #player-full-bleed-container {
>   background: none !important;
> }
> 
> html[data-ambientlight-enabled=true] ytd-app #player-full-bleed-container {
>   transition: background-color 0s 0.01s;
> }
> 
> html[data-ambientlight-enabled=true][data-ambientlight-immersive=true] ytd-watch-flexy[theater] #player-full-bleed-container.ytd-watch-flexy {
>   height: calc(100vh - 169px) !important;
>   max-height: calc(100vh - 169px) !important;
>   margin-top: 29px;
>   margin-bottom: 84px;
> }
> ```

How can I apply this fix?

**Comment by MoisteryMachine** [comment]
> How can I apply this fix?

Install an extension called Stylus, it lets you apply themes for web pages. There's some good YouTube related ones like coloured progress bars etc.

Go to YouTube and click the extension icon, then where it says write style for this site, click the word YouTube.
You'll get a new tab with two boxes on the right. In the lower box, paste the code between the { } where it says *code here*.
Give it a name in the text box on the left like "YouTube Ambilight fix" and click save. That should fix it!

**Comment by WesselKroos** [comment]
YouTube has changed the html once again this evening. The keep on changing but the store's review processes can't keep up. So, if you manually want to fix it again here are the css rules you'll need:

``` css
html[data-ambientlight-enabled=true][data-ambientlight-immersive=true] ytd-watch-flexy[theater] #full-bleed-container.ytd-watch-flexy {
  height: calc(100vh - 169px) !important;
  max-height: calc(100vh - 169px) !important;
  margin-top: 29px;
  margin-bottom: 84px;
}

html[data-ambientlight-enabled=true] ytd-app #full-bleed-container,
html[data-ambientlight-enabled=true] ytd-app #player-full-bleed-container {
  background: none !important;
}

html[data-ambientlight-enabled=true] #cinematics-full-bleed-container.ytd-watch-flexy {
  display: none !important;
}

html[data-ambientlight-enabled=true] ytd-app #full-bleed-container,
html[data-ambientlight-enabled=true] ytd-app #player-full-bleed-container {
  transition: background-color 0s 0.01s;
}
```
