### ISSUE TITLE
Add rounded corners of video in theater mode

### ISSUE THREAD

**Issue by ovojake** [WesselKroos/youtube-ambilight#219]
Wondering if it would be hard to add the rounded corners you see in default view to theater mode?

Great work on the extension btw

**Comment by WesselKroos** [comment]
Do you currently have rounded borders in theater view when the ambient light is disabled? Or do you want the option, because I don't think everyone wants those by default.

**Comment by ovojake** [comment]
No I don't have it without the extension. Just a suggestion that would be nice to have the ability to toggle. I wouldn't be surprised if youtube ends up adding it themselves since the default view is rounded

**Comment by WesselKroos** [comment]
Upon further inspection I won't implement this feature.
It goes against the philosophy of keeping the YouTube layout as close as possible to the original. And it will also be more complicated than just a single setting, because you could want rounded borders in small, theater or fullscreen mode, a specific roundness size. And I can image that some users also want the rounded borders in fullscreen when the video does not completely fill the screen because of removed borders or the video being a different aspect ratio than their screen. This introduces a lot of complexity.

As alternative you could install an extension with which you can customize the css on the webpage and add these css rules to get the rounded borders in theater mode:
``` css
ytd-watch-flexy[rounded-player-large][theater] #ytd-player.ytd-watch-flexy .html5-video-container,
ytd-watch-flexy[rounded-player-large][theater] #ytd-player.ytd-watch-flexy .html5-main-video {
    border-radius: 12px !important;
}
```
